==26== Memcheck, a memory error detector
==26== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==26== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==26== Command: python3.4 /usr/ichnosat/src/presentation/external_interface/start.py \> /usr/ichnosat/data_local/log/external_interface_pipe.log 2\> /usr/ichnosat/data_local/log/external_interface-err.log
==26== Parent PID: ==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x501C89: ??? (in /usr/bin/python3.4)
==25==  Address 0x623c020 is 1,200 bytes inside a block of size 3,892 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==25==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==25==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==  Address 0x6241020 is 160 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D5575: ??? (in /usr/bin/python3.4)
==25==    by 0x4CEB77: PyDict_SetItem (in /usr/bin/python3.4)
==25==    by 0x504537: PyObject_SetAttr (in /usr/bin/python3.4)
==25==    by 0x4EE867: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED25F: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==  Address 0x625b020 is 32,432 bytes inside a block of size 35,476 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==  Address 0x625c020 is 880 bytes inside a block of size 911 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x508876: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6293020 is 1,440 bytes inside a block of size 3,696 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==  Address 0x62c8020 is 7,088 bytes inside a block of size 8,470 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086CD: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==  Address 0x6322020 is 16 bytes inside a block of size 200 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9C23: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==  Address 0x6338020 is 5 bytes after a block of size 539 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==  Address 0x633a020 is 304 bytes inside a block of size 1,384 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==  Address 0x6357020 is 784 bytes inside a block of size 1,184 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==  Address 0x62f5020 is 384 bytes inside a block of size 1,608 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D62FC: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x53E11B: PyGrammar_AddAccelerators (in /usr/bin/python3.4)
==25==    by 0x53D973: PyParser_New (in /usr/bin/python3.4)
==25==    by 0x53CEA6: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB170: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4D6314: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x53E11B: PyGrammar_AddAccelerators (in /usr/bin/python3.4)
==25==    by 0x53D973: PyParser_New (in /usr/bin/python3.4)
==25==    by 0x53CEA6: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB170: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x53E11B: PyGrammar_AddAccelerators (in /usr/bin/python3.4)
==25==    by 0x53D973: PyParser_New (in /usr/bin/python3.4)
==25==    by 0x53CEA6: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB170: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x645f020 is 64 bytes inside a block of size 676 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53E11B: PyGrammar_AddAccelerators (in /usr/bin/python3.4)
==25==    by 0x53D973: PyParser_New (in /usr/bin/python3.4)
==25==    by 0x53CEA6: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB170: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55A7DF: ??? (in /usr/bin/python3.4)
==25==    by 0x54275D: PyNode_Free (in /usr/bin/python3.4)
==25==    by 0x5AB1A8: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x64ba020 is 32,384 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB170: PyParser_ASTFromFileObject (in /usr/bin/python3.4)
==25==    by 0x5AAFE1: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x573089: ??? (in /usr/bin/python3.4)
==25==    by 0x572CDE: ??? (in /usr/bin/python3.4)
==25==    by 0x571ED7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x64c0020 is 80 bytes inside a block of size 96 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x570FDC: ??? (in /usr/bin/python3.4)
==25==    by 0x56E021: ??? (in /usr/bin/python3.4)
==25==    by 0x55B4CE: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x58E55C: ??? (in /usr/bin/python3.4)
==25==    by 0x578B74: ??? (in /usr/bin/python3.4)
==25==    by 0x585F62: ??? (in /usr/bin/python3.4)
==25==    by 0x5874B3: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x64c3020 is 1,648 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FB13: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x58C430: ??? (in /usr/bin/python3.4)
==25==    by 0x5895A6: ??? (in /usr/bin/python3.4)
==25==    by 0x571DEA: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x64c0020 is 80 bytes inside a block of size 96 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x570FDC: ??? (in /usr/bin/python3.4)
==25==    by 0x56E021: ??? (in /usr/bin/python3.4)
==25==    by 0x55B4CE: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==25==    by 0x581995: ??? (in /usr/bin/python3.4)
==25==    by 0x55B33C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25==  Address 0x64c5020 is 224 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5810E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5AB018: PyRun_FileExFlags (in /usr/bin/python3.4)
==25==    by 0x5AA193: PyRun_SimpleFileExFlags (in /usr/bin/python3.4)
==25==    by 0x4CB4CA: Py_Main (in /usr/bin/python3.4)
==25==    by 0x4CA8EE: main (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4DB7D4: PyTuple_Pack (in /usr/bin/python3.4)
==25==    by 0x51663C: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE65C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED25F: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x512F05: PyObject_CallFunctionObjArgs (in /usr/bin/python3.4)
==25==  Address 0x64e3020 is 192 bytes inside a block of size 800 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D5575: ??? (in /usr/bin/python3.4)
==25==    by 0x4CEB77: PyDict_SetItem (in /usr/bin/python3.4)
==25==    by 0x4EF0E7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4DDE55: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==  Address 0x6508020 is 624 bytes inside a block of size 888 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4DDEB8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==  Address 0x6509020 is 16 bytes before a block of size 128 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x56C89C: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDE44: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3E0F: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x4E9EEF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E988A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6566020 is 4,144 bytes inside a block of size 4,769 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D47FC: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5492DE: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3F28: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x4E9EEF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E988A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4D47FC: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5492DE: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3F28: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x581237: PyInit__heapq (in /usr/bin/python3.4)
==25==    by 0x517565: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6574020 is 16 bytes after a block of size 800 alloc'd
==25==    at 0x4C28C20: malloc (vg_replace_malloc.c:296)
==25==    by 0x4D52A9: ??? (in /usr/bin/python3.4)
==25==    by 0x4D8186: PyDict_SetItemString (in /usr/bin/python3.4)
==25==    by 0x4DFDA7: PyModule_Create2 (in /usr/bin/python3.4)
==25==    by 0x58120F: PyInit__heapq (in /usr/bin/python3.4)
==25==    by 0x517565: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3E0F: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x581237: PyInit__heapq (in /usr/bin/python3.4)
==25==    by 0x517565: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6575020 is 2,672 bytes inside a block of size 4,769 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D47FC: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5492DE: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3F28: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x581237: PyInit__heapq (in /usr/bin/python3.4)
==25==    by 0x517565: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==  Address 0x654e020 is 1,344 bytes inside a block of size 1,864 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9C23: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086CD: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==  Address 0x654f020 is 768 bytes inside a block of size 2,152 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E98B4: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B6A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5308E6: ??? (in /usr/bin/python3.4)
==25==    by 0x52F386: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x65ac020 is 96 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F334C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x518EB6: ??? (in /usr/bin/python3.4)
==25==    by 0x4D9166: ??? (in /usr/bin/python3.4)
==25==    by 0x4D8F93: PySequence_List (in /usr/bin/python3.4)
==25==    by 0x51D27B: PyUnicode_Join (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x52F4AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x65ad020 is 704 bytes inside a block of size 1,835 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5308E6: ??? (in /usr/bin/python3.4)
==25==    by 0x52F386: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x565656: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x565656: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55A9C6: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x565656: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x65ba020 is 32,800 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x565656: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==25==    by 0x581995: ??? (in /usr/bin/python3.4)
==25==    by 0x587544: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x65c6020 is 32 bytes before a block of size 224 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x58580A: ??? (in /usr/bin/python3.4)
==25==    by 0x58757E: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x65c5020 is 1,312 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5867C4: ??? (in /usr/bin/python3.4)
==25==    by 0x5860F7: ??? (in /usr/bin/python3.4)
==25==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x65cb020 is 864 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x57BF4B: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x65d4020 is 64 bytes inside a block of size 545 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x57B8D6: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==25==    by 0x581995: ??? (in /usr/bin/python3.4)
==25==    by 0x579D2C: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x565679: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x65d2020 is 480 bytes inside a block of siz==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4DD10D: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x508894: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26== ==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x53F72F: _PyObject_GC_Resize (in /usr/bin/python3.4)
==25==    by 0x4EDA40: PyFrame_New (in /usr/bin/python3.4)
==25==    by 0x4F1AB4: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==  Address 0x6630020 is 304 bytes inside a block of size 1,384 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==25==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==25==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55A9C6: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x676c020 is 34,528 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x585867: ??? (in /usr/bin/python3.4)
==25==    by 0x58757E: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6777020 is 1,888 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x573089: ??? (in /usr/bin/python3.4)
==25==    by 0x586154: ??? (in /usr/bin/python3.4)
==25==    by 0x5860F7: ??? (in /usr/bin/python3.4)
==25==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x677d020 is 1,440 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x565429: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6759020 is 8 bytes after a block of size 520 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x51E481: ??? (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2B45: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x678b020 is 32 bytes inside a block of size 40 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x4D82DF: ??? (in /usr/bin/python3.4)
==25==    by 0x4CFF4D: PyType_Ready (in /usr/bin/python3.4)
==25==    by 0x4F7D54: ??? (in /usr/bin/python3.4)
==25==    by 0x4F77E4: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==    by 0x4F96BB: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x565403: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x584085: ??? (in /usr/bin/python3.4)
==25==    by 0x50720A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F298D: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x678b020 is 32 bytes inside a block of size 40 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x4D82DF: ??? (in /usr/bin/python3.4)
==25==    by 0x4CFF4D: PyType_Ready (in /usr/bin/python3.4)
==25==    by 0x4F7D54: ??? (in /usr/bin/python3.4)
==25==    by 0x4F77E4: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==    by 0x4F96BB: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x565403: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2B45: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==  Address 0x678c020 is 304 bytes inside a block of size 582 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x584085: ??? (in /usr/bin/python3.4)
==25==    by 0x50720A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F298D: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5302D4: ??? (in /usr/bin/python3.4)
==25==    by 0x52F386: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x6813020 is 0 bytes after a block of size 416 alloc'd
==25==    at 0x4C28C20: malloc (vg_replace_malloc.c:296)
==25==    by 0x4D52A9: ??? (in /usr/bin/python3.4)
==25==    by 0x5113F6: ??? (in /usr/bin/python3.4)
==25==    by 0x4F32F8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F334C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6812020 is 64 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F334C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x518E53: ??? (in /usr/bin/python3.4)
==25==    by 0x4D9166: ??? (in /usr/bin/python3.4)
==25==    by 0x4D8F93: PySequence_List (in /usr/bin/python3.4)
==25==    by 0x51D27B: PyUnicode_Join (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x54863E: ??? (in /usr/bin/python3.4)
==25==    by 0x545DE8: ??? (in /usr/bin/python3.4)
==25==    by 0x5441FD: ??? (in /usr/bin/python3.4)
==25==    by 0x54FD37: ??? (in /usr/bin/python3.4)
==25==    by 0x54F10A: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x6824020 is 16 bytes before a block of size 128 alloc'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x54B3F1: ??? (in /usr/bin/python3.4)
==25==    by 0x54AB69: ??? (in /usr/bin/python3.4)
==25==    by 0x54A4A5: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x500550: ??? (in /usr/bin/python3.4)
==25==    by 0x54863E: ??? (in /usr/bin/python3.4)
==25==    by 0x545DE8: ??? (in /usr/bin/python3.4)
==25==    by 0x5464A4: ??? (in /usr/bin/python3.4)
==25==    by 0x5464C0: ??? (in /usr/bin/python3.4)
==25==    by 0x554861: ??? (in /usr/bin/python3.4)
==25==    by 0x54FDFF: ??? (in /usr/bin/python3.4)
==25==    by 0x550A59: ??? (in /usr/bin/python3.4)
==25==    by 0x54FE39: ??? (in /usr/bin/python3.4)
==25==    by 0x54F10A: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x500568: ??? (in /usr/bin/python3.4)
==25==    by 0x54863E: ??? (in /usr/bin/python3.4)
==25==    by 0x545DE8: ??? (in /usr/bin/python3.4)
==25==    by 0x5464A4: ??? (in /usr/bin/python3.4)
==25==    by 0x5464C0: ??? (in /usr/bin/python3.4)
==25==    by 0x554861: ??? (in /usr/bin/python3.4)
==25==    by 0x54FDFF: ??? (in /usr/bin/python3.4)
==25==    by 0x550A59: ??? (in /usr/bin/python3.4)
==25==    by 0x54FE39: ??? (in /usr/bin/python3.4)
==25==    by 0x54F10A: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55A84A: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x6822020 is 34,384 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55A84A: ??? (in /usr/bin/python3.4)
==25==    by 0x55AB2B: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6822020 is 34,384 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55AA72: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==  Address 0x6822020 is 34,384 bytes inside a block of size 36,032 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x53D03E: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5759F9: ??? (in /usr/bin/python3.4)
==25==    by 0x576F3B: ??? (in /usr/bin/python3.4)
==25==    by 0x571C54: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6834020 is 384 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D62FC: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==25==    by 0x581995: ??? (in /usr/bin/python3.4)
==25==    by 0x579D2C: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4D6314: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==25==    by 0x581995: ??? (in /usr/bin/python3.4)
==25==    by 0x579D2C: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x541B3C: PyNode_AddChild (in /usr/bin/python3.4)
==25==    by 0x54130E: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53D2E8: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x541B3C: PyNode_AddChild (in /usr/bin/python3.4)
==25==    by 0x54130E: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53D2E8: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5857AD: ??? (in /usr/bin/python3.4)
==25==    by 0x58757E: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x68bd020 is 816 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5868D7: ??? (in /usr/bin/python3.4)
==25==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x68c3020 is 1,280 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x54863E: ??? (in /usr/bin/python3.4)
==25==    by 0x545DE8: ??? (in /usr/bin/python3.4)
==25==    by 0x5464A4: ??? (in /usr/bin/python3.4)
==25==    by 0x5464C0: ??? (in /usr/bin/python3.4)
==25==    by 0x554861: ??? (in /usr/bin/python3.4)
==25==    by 0x54FDFF: ??? (in /usr/bin/python3.4)
==25==    by 0x550A59: ??? (in /usr/bin/python3.4)
==25==    by 0x54FE39: ??? (in /usr/bin/python3.4)
==25==    by 0x54F10A: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==  Address 0x6911020 is 528 bytes inside a block of size 704 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x54B3F1: ??? (in /usr/bin/python3.4)
==25==    by 0x550996: ??? (in /usr/bin/python3.4)
==25==    by 0x54FE39: ??? (in /usr/bin/python3.4)
==25==    by 0x54F10A: ??? (in /usr/bin/python3.4)
==25==    by 0x542C13: PyAST_FromNodeObject (in /usr/bin/python3.4)
==25==    by 0x53B70E: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/b==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x5759F9: ??? (in /usr/bin/python3.4)
==26==    by 0x576F3B: ??? (in /usr/bin/python3.4)
==26==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x6e73020 is 1,664 bytes inside a block of size 2,048 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x57FB13: PyCode_Optimize (in /usr/bin/python3.4)
==26==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==26==    by 0x58752C: ??? (in /usr/bin/python3.4)
==26==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x573089: ??? (in /usr/bin/python3.4)
==26==    by 0x578A44: ??? (in /usr/bin/python3.4)
==26==    by 0x585F62: ??? (in /usr/bin/python3.4)
==26==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==  Address 0x6e79020 is 16 bytes after a block of size 32 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x4CEE15: ??? (in /usr/bin/python3.4)
==26==    by 0x562723: ??? (in /usr/bin/python3.4)
==26==    by 0x581A3B: ??? (in /usr/bin/python3.4)
==26==    by 0x587544: ??? (in /usr/bin/python3.4)
==26==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4D62FC: PyObject_Free (in /usr/bin/python3.4)
==26==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==26==    by 0x581995: ??? (in /usr/bin/python3.4)
==26==    by 0x579D2C: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x4D6314: PyObject_Free (in /usr/bin/python3.4)
==26==    by 0x581FEA: ??? (in /usr/bin/python3.4)
==26==    by 0x581995: ??? (in /usr/bin/python3.4)
==26==    by 0x579D2C: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x5759F9: ??? (in /usr/bin/python3.4)
==26==    by 0x576F3B: ??? (in /usr/bin/python3.4)
==26==    by 0x5860D0: ??? (in /usr/bin/python3.4)
==26==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==  Address 0x6ed4020 is 1,056 bytes inside a block of size 2,048 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x57FB13: PyCode_Optimize (in /usr/bin/python3.4)
==26==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==26==    by 0x58752C: ??? (in /usr/bin/python3.4)
==26==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==26==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==26==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==26==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==26==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==26==    by 0x53F72F: _PyObject_GC_Resize (in /usr/bin/python3.4)
==26==    by 0x4EDA40: PyFrame_New (in /usr/bin/python3.4)
==26==    by 0x4EC85B: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_E==25== Invalid read of size 4
==25==    at 0x5088F6: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ED12A: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F78A2: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2248: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6dc0020 is 1,552 bytes inside a block of size 2,533 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE036: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x53F72F: _PyObject_GC_Resize (in /usr/bin/python3.4)
==26==    by 0x4EDA40: PyFrame_New (in /usr/bin/python3.4)
==26==    by 0x4EC85B: PyEval_EvalCode==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5759F9: ??? (in /usr/bin/python3.4)
==25==    by 0x576F3B: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6e5d020 is 1,584 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x584085: ??? (in /usr/bin/python3.4)
==26==    by 0x50720A: ??? (in /usr/bin/python3.4)
==26==    by 0x4F298D: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x7a47020 is 16 bytes after a block of size 128 alloc'd
==26==    at 0x4C28C20: malloc (vg_replace_malloc.c:29==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x53F72F: _PyObject_GC_Resize (in /usr/bin/python3.4)
==25==    by 0x4EDA40: PyFrame_New (in /usr/bin/python3.4)
==25==    by 0x4EC85B: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6d42020 is 2,416 byte==26==    by 0x4F1B5E: PyEval_EvalFram==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bi==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x7a47020 is 16 bytes after a block of size 128 alloc'd
==26==    at 0x4C28C20: malloc (vg_replace_malloc.c:296)
==26==    by 0x512503: ??? (in /usr/bin/python3.4)
==26==    by 0x503FFE: P==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4CC7B4: _PyObject_GC_New (in /usr/bin/python3.4)
==25==    by 0x511DC1: ??? (in /usr/bin/python3.4)
==25==    by 0x4F6420: PyObject_GetAttr (in /usr/bin/python3.4)
==25==    by 0x4EDD6B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx ==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==26==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==26==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==26==    by 0x5308E6: ??? (in /usr/bin/python3.4)
==26==    by 0x52F386: ??? (in /usr/bin/python3.4)
==26==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==26==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==26==    by 0x52F4AC: ??? (in /usr/bin/python3.4)
==26==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4D5D93: ??? (in /usr/bin/python3.4)
==26==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==26==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==26==    by 0x4F334C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4D62FC: PyObject_Free (in /usr/bin/python3==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x5759F9: ??? (in /usr/bin/python3.4)
==25==    by 0x576F3B: ??? (in /usr/bin/python3.4)
==25==    by 0x5860D0: ??? (in /usr/bin/python3.4)
==25==    by 0x571C1B: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x7ae9020 is 1,968 bytes inside a block of size 2,048 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x57FAEF: PyCode_Optimize (in /usr/bin/python3.4)
==25==    by 0x57BAC5: ??? (in /usr/bin/python3.4)
==25==    by 0x58752C: ??? (in /usr/bin/python3.4)
==25==    by 0x571D7A: ??? (in /usr/bin/python3.4)
==25==    by 0x579CC8: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x57B8D6: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==25==    by 0x57B8D6: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x57BF55: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x57BF6D: ??? (in /usr/bin/python3.4)
==25==    by 0x579D21: ??? (in /usr/bin/python3.4)
==25==    by 0x571EF7: ??? (in /usr/bin/python3.4)
==25==    by 0x55B31C: PyAST_CompileObject (in /usr/bin/python3.4)
==25==    by 0x5653D1: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x51581E: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4ED9FE: PyFrame_New (in /usr/bin/python3.4)
==25==    by 0x4EC85B: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x888d020 is 240 bytes inside a block of size 416 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9727: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x5154C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B6A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==  Address 0x8918020 is 64 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4E9834: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B6A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==  Address 0x8d46020 is 176 bytes inside a block of size 588 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5EA1: ??? (in /usr/bin/python3.4)
==25==    by 0x4D47FC: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5492DE: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3F28: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x4E9EEF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E988A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8f26020 is 140,464 bytes inside a block of size 143,171 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D47FC: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5492DE: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3F28: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x4E9EEF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E988A: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x57405A: PyUnicode_Format (in /usr/bin/python3.4)
==25==    by 0x4F3678: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x9050020 is 64 bytes inside a block of size 280 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B54: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D4E34: _PyUnicodeWriter_Finish (in /usr/bin/python3.4)
==25==    by 0x573BC0: PyUnicode_Format (in /usr/bin/python3.4)
==25==    by 0x4F3678: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x9558020 is 32 bytes before a block of size 245,136 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4FEB3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8d3a020 is 0 bytes inside a block of size 1,462 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4FEB3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d38020 is 400 bytes inside a block of size 1,081 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4DD1DC: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4FEB2F: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4DD1F4: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4FEB2F: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x56EE30: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8da4020 is 5,504 bytes inside a block of size 6,176 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x56B6AC: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d62020 is 672 bytes inside a block of size 1,835 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D474D: _PyUnicodeWriter_PrepareInternal (in /usr/bin/python3.4)
==25==    by 0x5302D4: ??? (in /usr/bin/python3.4)
==25==    by 0x52F386: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDE44: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d2c020 is 400 bytes inside a block of size 602 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDE7: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4DE08F: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d91020 is 192 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9727: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x56EDF4: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d8e020 is 0 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9727: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x56EDF4: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDE55: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d94020 is 32 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9727: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDEA4: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x8d2d020 is 128 bytes inside a block of size 681 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x56C90D: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDE44: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D62F2: PyObject_Free (in /usr/bin/python3.4)
==25==    by 0x56EEF0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x56EDF4: ??? (in /usr/bin/python3.4)
==25==    by 0x4DDEB8: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8d8d020 is 736 bytes inside a block of size 1,568 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4D5575: ??? (in /usr/bin/python3.4)
==25==    by 0x4CEB77: PyDict_SetItem (in /usr/bin/python3.4)
==25==    by 0x4EF0E7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== 
==25== More than 100 errors detected.  Subsequent errors
==25== will still be recorded, but in less detail than before.
==25== Invalid read of size 4
==25==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x5A02A6: PyFrame_ClearFreeList (in /usr/bin/python3.4)
==25==    by 0x4DE531: ??? (in /usr/bin/python3.4)
==25==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==25==    by 0x4D31CC: _PyObject_GC_NewVar (in /usr/bin/python3.4)
==25==    by 0x4D2E04: PyTuple_New (in /usr/bin/python3.4)
==25==    by 0x4EE9FB: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8daa020 is 16 bytes after a block of size 32 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4CEE15: ??? (in /usr/bin/python3.4)
==25==    by 0x562723: ??? (in /usr/bin/python3.4)
==25==    by 0x5A5287: ??? (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3576: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6428020 is 54,560 bytes inside an unallocated block of size 56,256 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x57D0FA: PyByteArray_Resize (in /usr/bin/python3.4)
==25==    by 0x5F57BB: ??? (in /usr/bin/python3.4)
==25==    by 0x4EF019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x66ba020 is 1,392 bytes inside a block of size 1,880 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x57D0FA: PyByteArray_Resize (in /usr/bin/python3.4)
==25==    by 0x5F57BB: ??? (in /usr/bin/python3.4)
==25==    by 0x4EF019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x57D0FA: PyByteArray_Resize (in /usr/bin/python3.4)
==25==    by 0x5F57BB: ??? (in /usr/bin/python3.4)
==25==    by 0x4EF019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x5689BF: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2BCD: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED25F: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6259020 is 0 bytes after a block of size 98,560 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x51E481: ??? (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x5689C8: ??? (in /usr/bin/python3.4)
==25==    by 0x523AC6: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECF2D: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x5689E0: ??? (in /usr/bin/python3.4)
==25==    by 0x523AC6: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECF2D: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x5689BF: ??? (in /usr/bin/python3.4)
==25==    by 0x4F251C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x68e7020 is 14,416 bytes inside an unallocated block of size 17,728 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x5689BF: ??? (in /usr/bin/python3.4)
==25==    by 0x523AC6: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECF2D: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6506020 is 51,840 bytes inside an unallocated block of size 52,624 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5EA1: ??? (in /usr/bin/python3.4)
==25==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x5A1D77: ??? (in /usr/bin/python3.4)
==25==    by 0x4E848B: PyDict_DelItem (in /usr/bin/python3.4)
==25==    by 0x50486E: PyObject_SetAttr (in /usr/bin/python3.4)
==25==    by 0x4F121E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x9037020 is 293,584 bytes inside a block of size 295,472 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D3E0F: PyUnicode_DecodeUTF8Stateful (in /usr/bin/python3.4)
==25==    by 0x4E9EEF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E98B4: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x500550: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x500568: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x500550: ??? (in /usr/bin/python3.4)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x500568: ??? (in /usr/bin/python3.4)
==25==    by 0x508691: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2B45: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==  Address 0x6cdd020 is 0 bytes inside an unallocated block of size 992 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x7a29020 is 4,192 bytes inside an unallocated block of size 4,560 in arena "client"
==25== 
==28== Warning: invalid file descriptor 1048566 in syscall close()
==28== Warning: invalid file descriptor 1048567 in syscall close()
==28== Warning: invalid file descriptor 1048568 in syscall close()
==28== Warning: invalid file descriptor 1048569 in syscall close()
==28==    Use --log-fd=<number> to select an alternative log fd.
==28== Warning: invalid file descriptor 1048570 in syscall close()
==28== Warning: invalid file descriptor 1048571 in syscall close()
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x5953AE: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x6eb3020 is 16 bytes before a block of size 1,864 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==25==    by 0x4EA1EF: ??? (in /usr/bin/python3.4)
==25==    by 0x4E985B: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9947: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==25==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==25==    by 0x537524: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x500546: ??? (in /usr/bin/python3.4)
==25==    by 0x594813: ??? (in /usr/bin/python3.4)
==25==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==25==    by 0x591EAD: ??? (in /usr/bin/python3.4)
==25==    by 0x571942: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x7da1020 is 0 bytes after an unallocated block of size 8,544 in arena "client"
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAC2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==  Address 0x68b5020 is 624 bytes inside a block of size 640 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==25==    by 0x55AA1B: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (i==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==26==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==26==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26==  Address 0x6902020 is 352 bytes inside a block of size 640 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==26==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==26==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==26==    by 0x55AAC2: ??? (in /usr/bin/python3.4)
==26==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==26==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==26==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==  Address 0x6902020 is 352 bytes inside a block of size 640 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==26==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==26==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4D64F7: ??? (in /usr/bin/python3.4)
==26==    by 0x55AA1B: ??? (in /usr/bin/python3.4)
==26==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED106: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x6902020 is 352 bytes inside a block of size 640 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==26==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==26==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bi==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D6500: ??? (in /usr/bin/python3.4)
==25==    by 0x55AA1B: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: P==26== Invalid read of size 4
==26==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==26==    by 0x4DAB39: ??? (in /usr/bin/python3.4)
==26==    by 0x5EDF36: ??? (in /usr/bin/python3.4)
==26==    by 0x5ED0FA: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.==25== Invalid read of size 4
==25==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==25==    by 0x541B3C: PyNode_AddChild (in /usr/bin/python3.4)
==25==    by 0x54130E: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==  Address 0x8ce5020 is 16 bytes before a block of size 1,280 alloc'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x541587: PyParser_AddToken (in /usr/bin/python3.4)
==25==    by 0x53CFEA: ??? (in /usr/bin/python3.4)
==25==    by 0x53B6E1: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4DAB39: ??? (in /usr/bin/python3.4)
==25==    by 0x5EDF36: ??? (in /usr/bin/python3.4)
==25==    by 0x5ED0FA: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==  Address 0x9805020 is 16 bytes inside a block of size 96 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x503A7E: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x518E53: ??? (in /usr/bin/python3.4)
==25==    by 0x4D9166: ??? (in /usr/bin/python3.4)
==25==    by 0x4D8F93: PySequence_List (in /usr/bin/python3.4)
==25==    by 0x51D27B: PyUnicode_Join (in /usr/bin/python3.4)
==25==    by 0x4F244F: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4ED25F: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D5D93: ??? (in /usr/bin/python3.4)
==25==    by 0x4DAB39: ??? (in /usr/bin/python3.4)
==25==    by 0x5EDF36: ??? (in /usr/bin/python3.4)
==25==    by 0x5ED0FA: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE106: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F78A2: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2248: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==  Address 0x982e020 is 720 bytes inside a block of size 1,114 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x5EF357: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F78A2: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2248: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x4E851F: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE106: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F78A2: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2248: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==  Address 0x693c020 is 512 bytes inside a block of size 1,114 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x5EE0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x5ED0FA: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25==    by 0x4F78A2: ??? (in /usr/bin/python3.4)
==25==    by 0x4F2248: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x50EC62: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D4E34: _PyUnicodeWriter_Finish (in /usr/bin/python3.4)
==25==    by 0x574009: PyUnicode_Format (in /usr/bin/python3.4)
==25==    by 0x4FFCBC: ??? (in /usr/bin/python3.4)
==25==    by 0x522EC6: ??? (in /usr/bin/python3.4)
==25==    by 0x4F0C57: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==25==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==25==    by 0x4D4E34: _PyUnicodeWriter_Finish (in /usr/bin/python3.4)
==25==    by 0x574009: PyUnicode_Format (in /usr/bin/python3.4)
==25==    by 0x4FFCBC: ??? (in /usr/bin/python3.4)
==25==    by 0x522EC6: ??? (in /usr/bin/python3.4)
==25==    by 0x4F0C57: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==25==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4DD10D: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D6500: ??? (in /usr/bin/python3.4)
==25==    by 0x55A9C6: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D5D93: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECA2A: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4D5DAB: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECA2A: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x4D6500: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAC2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4D6518: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAC2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x55AAF2: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x4D6518: ??? (in /usr/bin/python3.4)
==25==    by 0x55AA1B: ??? (in /usr/bin/python3.4)
==25==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==25==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==25==    by 0x53A706: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x53A62D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25== 
==25== Conditional jump or move depends on uninitialised value(s)
==25==    at 0x500550: ??? (in /usr/bin/python3.4)
==25==    by 0x594813: ??? (in /usr/bin/python3.4)
==25==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==25==    by 0x591EAD: ??? (in /usr/bin/python3.4)
==25==    by 0x571942: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x581114: ??? (in /usr/bin/python3.4)
==25== 
==25== Use of uninitialised value of size 8
==25==    at 0x500568: ??? (in /usr/bin/python3.4)
==25==    by 0x594813: ??? (in /usr/bin/python3.4)
==25==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==25==    by 0x591EAD: ??? (in /usr/bin/python3.4)
==25==    by 0x571942: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x581114: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==25==    by 0x592A64: ??? (in /usr/bin/python3.4)
==25==    by 0x5ACDFC: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrame==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4DD1DC: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==26==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==26==    by 0x516AE8: ??? (in /usr/bin/python3.4)
==26==    by 0x503532: PyObject_GetIter (in /usr/bin/python3.4)
==26==    by 0x5690AC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x4DD1F4: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4DDDF8: ??? (in /usr/bin/python3.4)
==26==    by 0x4DD47E: ??? (in /usr/bin/python3.4)
==26==    by 0x516AE8: ??? (in /usr/bin/python3.4)
==26==    by 0x503532: PyObject_GetIter (in /usr/bin/python3.4)
==26==    by 0x5690AC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x50EC77: ??? (in /usr/bin/python3.4)
==26==    by 0x50E99F: ??? (in /usr/bin/python3.4)
==26==    by 0x52F4AC: ??? (in /usr/bin/python3.4)
==26==    by 0x4F2CA6: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x501C89: ??? (in /usr/bin/python3.4)
==26==    by 0x518471: _PyObject_CallFunction_SizeT (in /usr/bin/python3.4)
==26==    by 0xABA34B4: PyInit__psycopg (in /usr/lib/python3/dist-packages/psycopg2/_psycopg.cpython-34m-x86_64-linux-gnu.so)
==26==    by 0x5ABC49: _PyImport_LoadDynamicModule (in /usr/bin/python3.4)
==26==    by 0x5AB245: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x4D5DAB: ??? (in /usr/bin/python3.4)
==26==    by 0x4E884E: ??? (in /usr/bin/python3.4)
==26==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==26==    by 0x4F334C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x501C89: ??? (in /usr/bin/python3.4)
==26==    by 0x518471: _PyObject_CallFunction_SizeT (in /usr/bin/python3.4)
==26==    by 0xABA34B4: PyInit__psycopg (in /usr/lib/python3/dist-packages/psycopg2/_psycopg.cpython-34m-x86_64-linux-gnu.so)
==26==    by 0x5ABC49: _PyImport_LoadDynamicModule (in /usr/bin/python3.4)
==26==    by 0x5AB245: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4D6500: ??? (in /usr/bin/python3.4)
==26==    by 0x55A84A: ??? (in /usr/bin/python3.4)
==26==    by 0x55AB2B: ??? (in /usr/bin/python3.4)
==26==    by 0x53B71B: PyParser_ASTFromStringObject (in /usr/bin/python3.4)
==26==    by 0x5653B2: PyRun_StringFlags (in /usr/bin/python3.4)
==26==    by 0x53A706: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x501C89: ??? (in /usr/bin/python3.4)
==26==    by 0x518471: _PyObject_CallFunction_SizeT (in /usr/bin/python3.4)
==26==    by 0xABA34B4: PyInit__psycopg (in /usr/lib/python3/dist-packages/psycopg2/_psycopg.cpython-34m-x86_64-linux-gnu.so)
==26==    by 0x5ABC49: _PyImport_LoadDynamicModule (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x500550: ??? (in /usr/bin/python3.4)
==26==    by 0x594813: ??? (in /usr/bin/python3.4)
==26==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==26==    by 0x591EAD: ??? (in /usr/bin/python3.4)
==26==    by 0x571942: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==26==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x500568: ??? (in /usr/bin/python3.4)
==26==    by 0x594813: ??? (in /usr/bin/python3.4)
==26==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==26==    by 0x591EAD: ??? (in /usr/bin/python3.4)
==26==    by 0x571942: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE4A7: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x511FAE: ??? (in /usr/bin/python3.4)
==26==    by 0x5115A0: ??? (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x4D5D93: ??? (in /usr/bin/python3.4)
==26==    by 0x592A64: ??? (in /usr/bin/python3.4)
==26==    by 0x5ACDFC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x4D5DAB: ??? (in /usr/bin/python3.4)
==26==    by 0x592A64: ??? (in /usr/bin/python3.4)
==26==    by 0x5ACDFC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x500546: ??? (in /usr/bin/python3.4)
==26==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==26==    by 0x59490B: ??? (in /usr/bin/python3.4)
==26==    by 0x5927AE: ??? (in /usr/bin/python3.4)
==26==    by 0x5ACDFC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x9fc1020 is 80 bytes inside a block of size 96 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==26==    by 0x4F251C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4D5D89: ??? (in /usr/bin/python3.4)
==26==    by 0x592A64: ??? (in /usr/bin/python3.4)
==26==    by 0x5ACDFC: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F967A: ??? (in /usr/bin/python3.4)
==26==  Address 0xa273020 is 64,416 bytes inside a block of size 66,084 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26== 
==26== Conditional jump or move depends on uninitialised value(s)
==26==    at 0x5689C8: ??? (in /usr/bin/python3.4)
==26==    by 0x4F251C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Use of uninitialised value of size 8
==26==    at 0x5689E0: ??? (in /usr/bin/python3.4)
==26==    by 0x4F251C: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x500546: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3576: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0xd734020 is 65,424 bytes inside a block of size 65,569 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
